### ISSUE TITLE
Relecture du cahier des charges - prestataire

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#16]
Le cahier des charges est terminé, en cours de validation par le client.
Une relecture de ton côté est nécessaire pour validation ou questions.

**Comment by Royoyo** [comment]
J'ai relu le cahier des charges en profondeur , tout me semble couvert.

**Comment by taophp** [comment]
J'attends la validation du client (#15) au cas où il demande un changement dans le cahier des charges, et je clôturerais le ticket si tout est bon.
