### ISSUE TITLE
Organisation de la maquette fonctionnelle

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#17]
- [x] Établir la liste des scénarios à envisager pour la maquette fonctionnelle
- [x] Pour chaque scénario, établir la liste des pages et leurs liaisons
- [x] Pour chaque page, créer un ticket, l'affecter à un développeur de l'application (mais pas à toi, consacre-toi à la coordination),
- [ ] Suivre l'avancement de chacun de ces tickets et la cohérence de l'ensemble, m'avertir en cas de difficulté
- [ ] valider le résultat
- [ ] m'inviter à valider

Lorsque moi aussi j'aurai valider, ce sera le tour du client. Je souhaite le faire le 21 janvier. Bon courage.

**Comment by Royoyo** [comment]
J'ai établi une liste de pages html à produire sous la forme d'un schéma que l'ont peut retrouver [ici](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf) ainsi que terminer d'assigner un ticket à chaque membre de classe.

**Comment by taophp** [comment]
Très bien. Continuons.
