### ISSUE TITLE
Tutoriel rapide sur l'utilisation de Github

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#19]
Alors avant tout, pour ceux qui ne l'ont pas encore fait, je vais vous demander d'installer le client github en suivant ce lien : https://windows.github.com/

Une fois le client installé et vous êtes connecté sur votre compte vous allez devoir cloner le dossier "ProjetSio" du site :
![explicationclientgithub](https://cloud.githubusercontent.com/assets/6312371/5697450/ff99ecfe-99f0-11e4-866d-17c9095eee56.PNG)

![explicationclientgithub2](https://cloud.githubusercontent.com/assets/6312371/5697452/29d145a8-99f1-11e4-851e-cc217909129e.PNG)

Et voilà ! Normalement vous avez une vue historique  de tous les commits ( "rajouts") du projet !

Maintenant pour ce qui est vraiment cool : Vous allez pouvoir rajouter des fichiers ou faire des changements  au projet directement sur votre pc ! 

On va faire un petit test pour être sûr que vous voyez comment ça fonctionne : j'ai créé à la racine du repository un dossier "Test Commit Github" , je voudrai que vous fassiez  tous un commit avec un fichier texte vide nommé selon le même principe que celui déjà présent. 
Petit tuto en image :

* Création du fichier: ![explicationclientgithub3](https://cloud.githubusercontent.com/assets/6312371/5697498/b601815e-99f2-11e4-9d45-e13122447e51.PNG)
* Cliquez sur la petite flèche entourée en bleu pour voir les détails de votre commit, une fois que vous êtes satisfait de votre code mettez un titre à la place de "Summary" et cliquez sur "Commit to master"
* ![explicationclientgithub4](https://cloud.githubusercontent.com/assets/6312371/5697525/95edb6a2-99f3-11e4-8ba5-a2004c8bbef3.PNG)
* Finalement, pour mettre votre commit en ligne, vous n'avez plus qu'à cliquer sur le petit "sync"
 indiqué dans l'image ci-dessous 
![explicationclientgithub5](https://cloud.githubusercontent.com/assets/6312371/5697543/16f59da0-99f4-11e4-9be3-a6e96b3268a3.PNG)

Voilà! Normalement c'est tout ce que vous devez savoir pour participer au projet!
Si vous voulez une explication plus en profondeur de l'outil github voici un petit tutoriel en français : 
http://christopheducamp.com/2013/12/15/github-pour-nuls-partie-1/

@nicolasdeu @Romain-Spielmann @Kevin-niva  @penardc @Draimon @Juustine @NicolasJab @fromgi @HuberR67 @docdanny67

**Comment by Royoyo** [comment]
Personnes ayant complétées le tuto : Romain... et puis c'est tout! Aller les gars, j'aimerai bien avoir un petit commit de la part de tous le monde!

**Comment by Draimon** [comment]
Des que j'aurais le temps poulet

Damien Raimon
