### ISSUE TITLE
Règle * à supprimer

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#20]
J'ai vu que le fichier https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Template/style.css commençait par une règle "*". Cela n'est pas interdit par la norme CSS, par contre il s'agit d'une pratique déconseillée car elle nécessite un travail important de la part du navigateur. Il y a moyen de faire autrement.
Par ailleurs, à la première ligne, j'ai vu une définition de charset. Si vous suivez les bonnes pratiques (uniquement des caractères standard non-accentués) cette déclaration est inutile.

**Comment by Royoyo** [comment]
J'ai supprimé la définition du charset et changé le code css,est ce qu'est cette manière de faire est moins lourde pour le navigateur?
(https://github.com/Royoyo/ProjetSio/commit/be2a2b7f940c66b66123fce90c527e7915ba93c2)

**Comment by taophp** [comment]
Eh non, la règle `*` est toujours présente et s'applique à tous les éléments en plus de `body`. Il faut ne garder que `body` en ajoutant éventuellement d'autres éléments, mais en spécifiant lesquels.

**Comment by taophp** [comment]
Si tu tiens à faire une redéfinition globale du style des navigateurs pour obtenir un rendu similaire voire identique sur tous, fait une recherche sur "reset css". Ils ont en général l'un ou l'autre défaut, mais cela te donnera une meilleure base.

**Comment by Royoyo** [comment]
L'idée était de garder ce formatage pour tous les éléments que les autres mettront par dessus le template en fait. On peut toujours changer cela plus tard non?

**Comment by Royoyo** [comment]
Ah, "reset css" il me semble que j'avais lu quelque chose là dessur,  je vais faire une recherche de suite.

**Comment by taophp** [comment]
Le problème de cette règle est qu'elle redéfinit le **style** et la **taille** de **tous** les éléments, y compris ceux qui ont une bonne raison d'avoir le style qu'ils ont. Ici, dans le html affiché, il n'y a plus moyen de distingue les textes mis en évidence de ceux qui ne le sont pas, les titres du corps, etc. Du coup, le visuel obtenu ne correspondra pas à la sémantique.
Il vaut mieux suivre le style par défaut des navigateurs, ou utiliser un reset css bien foutu, quitte à corriger au fur et à mesure ce qui ne va pas, que de réduire à néant tous les styles préexistant, car cela induit  les maquettistes en erreur et surtout, les erreurs sémantiques deviennent invisibles.

**Comment by Royoyo** [comment]
J'ai enlevé la règle `*`, je comprends mieux pourquoi il faut l'éviter maintenant, merci.

**Comment by taophp** [comment]
Quelle révision ?

**Comment by Royoyo** [comment]
80e43cf5eb0c7448002ce7cc6b227373b570b5e2
