### ISSUE TITLE
Que se passe-t-il ?

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#21]
Je ne vois rien bouger sur ce projet. La dernière activité sensible remonte à presque 15 jours, et c'était moi.
Lors de son seul commit, il y a 19 jours (https://github.com/Royoyo/ProjetSio/commit/74c3cb6488c6a5c250dfe4f0a2c099aad86b6795) le client a indiqué en commentaire : "Je pense qu'il faudrait envisager l'élaboration d'une 1ère solution limitée pour la mettre rapidement en test avec 2 ou 3 profs" Cela a-t-il été pris en compte ? pourra-t-on lui propose rapidement une maquette fonctionnelle ? ou dois-je informer le client que le projet est abandonné ?
Je vous rappelle que les développeurs ont décidé de faire de ce qui n'était d'abord qu'un exercice de longue haleine leur PPE. Il y a donc un enjeu fort pour vous - à moins que le BTS ne soit une question secondaire pour vous.
@Royoyo : je veux d'urgence un point sur la situation par mail, avec la liste des problèmes et des propositions de remédiation. Je propose qu'à l'avenir ces points soient régulier, et que j'ai un état de l'avancement au moins une fois par semaine par mail, plus si nécessaire.

**Comment by Royoyo** [comment]
Je pense qu'une des raisons qui fait que rien n'a bougé ces deux dernières semaine est que beaucoup de professeurs se sont rappelés qu'ils avaient besoin de notes pour le 1er semestre...ce qui s'est traduit par beaucoup plus de travail pour les élèves. Après ça ne reste qu'une excuse, c'est vrai.

Pour ce qui est de répondre au client ((https://github.com/Royoyo/ProjetSio/commit/74c3cb6488c6a5c250dfe4f0a2c099aad86b6795) je ne sais pas si cela sera possible rapidement d'avoir une maquette fonctionnelle. Vu que je viens d'assigner la plus grande partie des tâches , je pense qu'on sera fixé la semaine prochaine selon la vitesse à laquelle les gens coderont.

A partir de cette semaine, je vous ferai un rapport toutes les fins de semaines sur l'avancement du projet et un récapitulatif des problèmes rencontrés.

**Comment by taophp** [comment]
OK. Merci. Continuons comme ça.
