### ISSUE TITLE
Vue Admin - Page liste des utilisateur

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#22]
Je te donne la page par défaut de l'admin à faire, tu peux te référer au  [cahier des charges](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-du-r%C3%B4le-administrateur) à la section fonctionnalité du rôle d'admin et à ce [schéma](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf) pour t'aider.
Si tu as des question par rapport à la page, pose les ici.

**Comment by Romain-Spielmann** [comment]
On reste bien seulement sur la maquette fonctionnelle pour le moment ?
Je créer uniquement la page qui permet l'affichage des différents utilisation ou aussi celle pour les créer/consulter/supprimer etc... ?

**Comment by taophp** [comment]
Oui, car la maquette fonctionnelle doit être validée dans son ensemble par le client.
Par contre, rien n'empêche de travailler le fond (les modèles ou la base de données par exemple).

**Comment by Royoyo** [comment]
Si tu te sens motivé, tu peux créer les autres pages de la gestion d'utilisateurs. Pour l'instant je n'ai alloué qu'une page par personne mais ça ne t'empêche pas d'avancer plus vite si tu en as envie.

Une fois que tu auras commit cette page, je t'en affecterai une (voir des) autre(s)

**Comment by Draimon** [comment]
Ola ola minute papillon j'ai meme pas fait mon commit test lol

Damien Raimon

**Comment by Royoyo** [comment]
Damien, t'as répondu à un ticket qui ne t'es pas assigné...^^. Si tu veux éviter de te faire spam par des messages qui ne te sont pas adressés, tu peux suivre les instructions [ici]( https://github.com/Royoyo/ProjetSio/issues/18)

**Comment by Romain-Spielmann** [comment]
Je pensais utilisé un tableau pour afficher la liste des utilisateurs, et j'ai donc penser à un plugin jQuery que j'utilise au travail qui est DataTables. http://datatables.net/
Il permet de filter avec une fonction de recherche ou d'ordonner les lignes par ordre croissant/décroissant en fonction d'une colonnes.
Nous en sommes pas encore à ce stade là mais je voulais juste savoir si c'étais possible d'utiliser un plugin de ce genre ou non.

**Comment by taophp** [comment]
La maquette fonctionnelle doit permettre de valider que toutes les fonctionnalités sont accessibles et utilisables confortablement. Il s'agit donc d'ergonomie, pas de design. Par ailleurs, pour cette application, le client n'a pas demandé de design, ce qui signifie que vous êtes libres de ce côté - toutefois, cela signifie aussi qu'il ne faut pas perdre de temps là-dessus.
Par ailleurs, l'utilisation de composants logiciels extérieurs dans une application fait partie des exigences du référentiel. Il est donc possible, et même de ce point de vue, souhaitable d'utiliser un plugin jQuery.
Enfin, avant d'utiliser un tel plugin, il faut se poser quelques questions : la fonctionnalité assurée par ce plugin est-elle accessible sans lui (c'est-à-dire sans JavaScript en l'occurrence) ? si non, le client est-il d'accord que cette fonctionnalité puisse manquer aux utilisateurs ne pouvant en bénéficier ? Dans cette question, il faut penser que certains utilisateurs ne le font pas tous par choix et tout simplement pas en mesure de changer cet état de fait. Je ne sais à peu près rien du support de JavaScript par les navigateurs pour mal-voyants. Que se passerait-il si un jour l'IFIDE avait recours à un enseignant aveugle ?

**Comment by Royoyo** [comment]
J'ai fait un petit tour sur le site du plugin, vraiment intéressant, je pense que je vais l'utiliser pour d'autres projets.

Pour l'instant je pense qu'il vaut mieux créer quelque chose qui ne dépend pas forcément d'un plugin javascript. On peut toujours l'ajouter par la suite et l'utiliser comme affichage de base et laisser ce que l'on construit maintenant comme affichage si les scripts sont désactivés. 

@taophp  Cela vous parait convenable?

**Comment by taophp** [comment]
Oui.

**Comment by Royoyo** [comment]
Je pense que c'est bon pour cette page.

Je valide la version de ton commit 5f8308a485af0caf043d6a9912314257149f67a1

Je t'assigne une autre page ( voir cette [issue] (https://github.com/Royoyo/ProjetSio/issues/38))
