### ISSUE TITLE
Vue Login - Pages login & Réinitialisation mot de passe

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#23]
Hey Damien! Vu que tu avais l'air très motivé à faire du html l'autre fois, je te donne pas une , mais deux pages à faire!
Utilise les infos du cahier des charges à la section ["fonctionnalités communes à chaque rôle"](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-communes-%C3%A0-chaque-r%C3%B4le) et de ce [schéma] (https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf) pour t'aider!
Si tu as des questions, surtout n'hésite pas à les poser en répondant ici. Je répondrai le plus vite possible.

**Comment by Draimon** [comment]
Mais j'ai rien pitter a github serieux tu peux pas m'envoyer des pieces jointe par mail?

Damien Raimon

**Comment by Royoyo** [comment]
Non, faut que ça soit fait par github pour que le prof voit les avancements
de chacun. T'as regardé le petit tuto que j'ai fait pour vous?

https://github.com/Royoyo/ProjetSio/issues/19

Le 26 janvier 2015 22:18, Draimon <notifications@github.com> a écrit :

> Mais j'ai rien pitter a github serieux tu peux pas m'envoyer des pieces
> jointe par mail?
>
> Damien Raimon
>
> > Le 26 janv. 2015 à 21:27, Guillaume Haag <notifications@github.com> a
> écrit :
> >
> > Hey Damien! Vu que tu avais l'air très motivé à faire du html l'autre
> fois, je te donne pas une , mais deux pages à faire!
> > Utilise les infos du cahier des charges et de ce schéma pour t'aider!
> > Si tu as des questions, surtout n'hésite pas à les poser en répondant
> ici. Je répondrai le plus vite possible.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Royoyo/ProjetSio/issues/23#issuecomment-71540209>.
>



-- 
Haag Guillaume
IT Specialist
Mobile: 0636644542
Email: guillaume.haag.pro@gmail.com
Website: http://guillaumehaag.fr
<http://www.facebook.com/guillaumehaag>
<http://fr.linkedin.com/in/guillaumehaag>
<http://twitter.com/GuillaumeHaag>  <http://github.com/royoyo>

**Comment by Royoyo** [comment]
Si vraiment ça va pas, je peux faire une session skype explicative avec
partage d'écran


Le 26 janvier 2015 22:20, Haag Guillaume <guillaume.haag.pro@gmail.com> a
écrit :

> Non, faut que ça soit fait par github pour que le prof voit les
> avancements de chacun. T'as regardé le petit tuto que j'ai fait pour vous?
>
> https://github.com/Royoyo/ProjetSio/issues/19
>
> Le 26 janvier 2015 22:18, Draimon <notifications@github.com> a écrit :
>
> Mais j'ai rien pitter a github serieux tu peux pas m'envoyer des pieces
>> jointe par mail?
>>
>> Damien Raimon
>>
>> > Le 26 janv. 2015 à 21:27, Guillaume Haag <notifications@github.com> a
>> écrit :
>> >
>> > Hey Damien! Vu que tu avais l'air très motivé à faire du html l'autre
>> fois, je te donne pas une , mais deux pages à faire!
>> > Utilise les infos du cahier des charges et de ce schéma pour t'aider!
>> > Si tu as des questions, surtout n'hésite pas à les poser en répondant
>> ici. Je répondrai le plus vite possible.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Royoyo/ProjetSio/issues/23#issuecomment-71540209>.
>>
>
>
>
> --
> Haag Guillaume
> IT Specialist
> Mobile: 0636644542
> Email: guillaume.haag.pro@gmail.com
> Website: http://guillaumehaag.fr
> <http://www.facebook.com/guillaumehaag>
> <http://fr.linkedin.com/in/guillaumehaag>
> <http://twitter.com/GuillaumeHaag>  <http://github.com/royoyo>
>



-- 
Haag Guillaume
IT Specialist
Mobile: 0636644542
Email: guillaume.haag.pro@gmail.com
Website: http://guillaumehaag.fr
<http://www.facebook.com/guillaumehaag>
<http://fr.linkedin.com/in/guillaumehaag>
<http://twitter.com/GuillaumeHaag>  <http://github.com/royoyo>

**Comment by Royoyo** [comment]
En plus de la suppression des champs inutiles, il faudrait déplacer ton code javascript dans une balise <script></script> à l'intérieur de la balise <head></head>

**Comment by Royoyo** [comment]
La page de ton dernier commit 5511a109dd13291666ddd24591c42ba029f2e9ea  respecte bien les consignes. 

Par contre tu n'avais toujours déplacer ton code javascript dans une balise <script>, je me suis permis de le faire  avec ce commit  : 1d5dad5c1df740648a16ade348d83b465230937b

Jette un coup d'oeil pour bien comprendre ce que j'attendais de toi pour le code javascript.

**Comment by taophp** [comment]
Il y avait un problème avec le JavaScript, corrigé par @Draimon corrigé en https://github.com/Royoyo/ProjetSio/commit/5cefa5cd24a8762c1c8d1af9c68711b018d368ac#diff-5b2e6c62463399448307ffcaf411ea28.

**Comment by Royoyo** [comment]
Très bien , la page de login me parait bonne maintenant. Je valide pour la maquette fonctionnelle.
