### ISSUE TITLE
Vue Admin - Page création d'utilisateur

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#24]
Tiens Kevin, je te donne ce petit formulaire pour la création d'utilisateur à faire. 
Utilise le [cahier des charges](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-du-r%C3%B4le-administrateur) à la section fonctionnalités du rôle d'admin et ce [schéma](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf) pour mener à bien ta mission!
Si tu as des question, n'hésite pas à les poser ici. Je répondrai rapidement.

**Comment by Royoyo** [comment]
Vu que @Romain-Spielmann  a déjà fait cette page. Je la lui assigne. 

Romain, je vois qu'actuellement dans ta page create.html il y a un label avec une checkbox "Créer un nouvel utilisateur". Tu pourrais m'expliquer quel est l'intérêt de cette checkbox?

**Comment by Romain-Spielmann** [comment]
Cette checkbox permet de créer un nouvel utilisateurs, si la case est cochée lors du submit la page afficher sera de nouveau le formulaire pour ajouter un nouvel utilisateur et s'il n'est pas coché la page affiché sera la liste. Cela répond au cahier des charges

> Une case à cocher supplémentaire permet, si elle est cochée et que la création de l'utilisateur réussie, de réafficher le même formulaire à nouveau vierge pour créer un autre utilisateur. Dans ce cas là, la case est à nouveau cochée, ce qui permet d'enchaîner la création d'utilisateurs. Si la case n'est pas cochée, alors la page listant les utilisateurs s'affiche.

**Comment by Royoyo** [comment]
Ok, je valide ta page pour la maquette fonctionnelle. On verra pour rendre ça plus claire plus tard
