### ISSUE TITLE
Vue Planificateur - Gestion des classes - Affichage

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#27]
Salutation petit guerrier! J'espère que t'es en forme, parce qu'il y a du HTML sur la planche!
Je voudrai que me fasses quelque chose de bien précis : l'affichage des classes d'élèves.
N'oublie pas de regarder la section [fonctionnalités du planificateur](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-du-r%C3%B4le-administrateur) dans le cahier des charges et le petit [schéma](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf)  du site que j'ai concocté pour t'aider.
Si tu as des question, je suis là pour te répondre!

**Comment by Royoyo** [comment]
Dès que tu fais quelque chose indique le ici et copie/colle le commit ici.
Je le fais pour toi cette fois : 2d150170a0aa58b816b3256c3d5b31f5a1d11c0c

Déjà bravo pour le style du tableau, il fallait qu'on fasse quelque chose de fonctionnel d'abord, mais j'apprécie l'effort.

Maintenant au modification à faire : 
* D'abord tu peux retirer les colonnes date de début et date de fin et seulement garder la colonne année, elle suffit pour ce tableau
* Je ne vois pas de page création/modification de classe, tu en as fait une ? Si non, il faudra en faire une .
* Ensuite il faut pouvoir cliquer sur une classe pour atterrir sur une autre page qui va lister trois choses : les matières enseignées , les enseignants et les années assignées à cette classe. Il faut aussi pouvoir rajouter ou supprimer chacune de ces choses. 

Donc ça te laisse encore deux petites pages à faire, bon courage!

**Comment by Qbergamin** [comment]
9e49619233efa0ca243630262fcf4755d8774114
changement effectué maître
la troisième page suit bientôt
