### ISSUE TITLE
Vue Planificateur - Gestion des matières enseignées - Affichage

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#28]
Salutation Daniel!
Voilà la tâche qui t'incombe pour ce projet: Créer la page qui affiche les matières enseignées disponibles. 
Pour mieux comprendre ce que je te demande va voir le cahier des charges , [section fonctionnalités du planificateur](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-du-r%C3%B4le-administrateur) et jette un coup d'oeil à ce [schéma](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Planification_HTMLvsdx.pdf) du site.
Si tu as des questions ou si tu veux des précisions , n'hésite pas à les demander sur cette page. Je répondrai le plus rapidement possible!

**Comment by docdanny67** [comment]
Salut Guillaume,
cela convient-il ?...

**Comment by Royoyo** [comment]
Je viens de jeter un coup d'oeil à tes trois fichiers , pas mal!  :+1: 

Pour les choses qu'il faudrait changer : 
* J'aimerai réserver la partie header aux informations qui précisent sur quelle page l'utilisateur se trouve, donc le titre, à la rigueur le lien "page précédente". Pas les les liens vers modification, création...
* Je vois que tu listes matière1,matière2... puis une case vide. Tu t'imagines ça comment avec des vrais matières? Tu remplaces "matière1" par le nom de la matière? A quoi sert à la case vide alors?
* Peut être que l'ont peut rajouter le lien "modification" à côté de chaque matière? ça rendrait le changement de page plus rapide.

Je vois que tu as bricolé un peu de javascript avec ta troisième version, c'est sympa, mais ça risque de causer des problèmes si l'utilisateur désactive les scripts...Donc concentre toi d'abord sur le code Html. :) 

J'ai rajouté une nouvelle classe dans le style.css ,  "centered"  , n'importe quel élément à l'intérieur de l'id "content" sera centré s'il utilise cette classe. Fais en bon usage!

**Comment by Royoyo** [comment]
Petite chose en plus : essaie d"évite un maximum l'attribut style dans tes balises. Crée une class ou un id  dans le fichier style.css global si tu as besoin d'appliquer un style particulier.

**Comment by Royoyo** [comment]
Dès que tu avances sur le projet, essaie de mettre ton commit dans le ticket qui t'es assigné. 
Je le fais pour toi cette fois : a1a8903bfb31f8ced085cfdf1dba2d7f028c69d5

J'aime beaucoup ta page 1,  je pense qu'on va garder celle là comme base.

Quelques petites choses à modifier :
* Crée aussi un nouveau dossier avec l'intitulé "Gestion matières enseignées" et met y tes fichiers , ça permettra une meilleure lisibilité de l'ensemble.
* Je vois que tu utilises la balises \<input> dans ton code pour afficher les matières. Ici on ne va que afficher les matières , une simple cellule de tableau suffit.
* Il faut quand tu cliques sur la matière avoir une liste de tous les enseignants qui sont affectées à cette matière et la capacité de pouvoir en rajouter et en retirer. ( C'est une autre page à faire)

**Comment by Royoyo** [comment]
commit : ec150b5e7288724621bb156b1c2fd8528fa88cc1

Bien, il me faut quand même le tableau qui liste les enseignants affectés dans la page de détails!
