### ISSUE TITLE
SQL - Années scolaire/ semaines d'enseignement / demi-journée de cours/ demi-journée...

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#31]
.../jours de fermeture/demi-journées d'indisponibilités d'enseignants

Ca en fait un titre à rallonge!
Salut Nicolas, aujourd'hui c'est pas de l'ORM que je vais te faire faire! ;)
Je vais pas non plus te demander de me sortire les tables SQL comme ça. J'aimerai que tu réfléchisses de quelle manière nous allons pouvoir transposer ces objets métiers dans notre base de données.
Aide toi de la section objets métiers dans le [cahier des charges](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#fonctionnalit%C3%A9s-du-r%C3%B4le-administrateur)
Dès que tu as des idées, n'hésite pas à les poster ici. La même chose si tu as des questions!

**Comment by nicolasdeu** [comment]
Salut.
Ok, pas de probleme, en gros tu veux le shema des tables (avec id)avec leurs liens ?
Je te fait sa pour mercredi soir.

**Comment by Royoyo** [comment]
Oui, en gros . Mais j'aimerai que tu commit dès que tu avances un peu, de
préférence dans le dossier SQL  ^^

Comme ca , s'il y a quelque chose qui cloche , on peut essayer d'arranger
ca  directement .

**Comment by Royoyo** [comment]
J'espère que j'aurai droit à ton commit ce week end! Si tu as encore des question tu sais comment me contacter
