### ISSUE TITLE
Style et templates

### ISSUE THREAD

**Issue by Draimon** [Royoyo/ProjetSio#32]
Ecoute Guillaumej'ai rien capté à ton template et je ne retrouve quel est ma mission.
Je t'ai mis mon HTML de formulaire d'inscription avec Javascript pour verif erreur.
Regarde le et dis moi Steup comment le mettre en forme
Je fais ça entre de taf au boulot
Je ne peut pas m'attarder et tu reponds pas au tel.
N'hesite pas a me tel dès que tu peux afin de m'expliquer.

**Comment by Royoyo** [comment]
Je peux pas répondre quand je suis au boulot!
Le 28 janv. 2015 16:40, "Draimon" <notifications@github.com> a écrit :

Ecoute Guillaumej'ai rien capté à ton template et je ne retrouve quel est
ma mission.
Je t'ai mis mon HTML de formulaire d'inscription avec Javascript pour verif
erreur.
Regarde le et dis moi Steup comment le mettre en forme
Je fais ça entre de taf au boulot
Je ne peut pas m'attarder et tu reponds pas au tel.
N'hesite pas a me tel dès que tu peux afin de m'expliquer.

—
Reply to this email directly or view it on GitHub
<https://github.com/Royoyo/ProjetSio/issues/32>.

**Comment by Royoyo** [comment]
J'ai changé légèrement ta page avec ce commit : 85f6444d3cdd8bec64a0e3565ef729e7fa7c6947

J'ai centré ton form dans le div, c'était pas possible de le faire sans css et j'avais oublié de créer une classse pour ça dans mon template. A partir de maintenant si tu veux centrer quelque chose dans le div avec l'id "content" crée simplement ton contenu dans un div avec l'id "centered".

Par contre ce qu'il faut que tu fasses, c'est une page de login, donc seulement les champs nom d'utilisateur et mot de passe sont utiles, je te laisse arranger ça.

**Comment by Royoyo** [comment]
Si tu as des questions, posent les sur ton ticket ici. Je suis gentil je te file un raccourci : [voili voilou](https://github.com/Royoyo/ProjetSio/issues/23)

Je ferme ce ticket.

**Comment by taophp** [comment]
Étant donné qu'un id doit être unique dans une page, utiliser un id pour centrer un élément en CSS interdit de centrer deux fois dans la même page, à moins de créer autant d'id que nécessaire... Il **faut** utiliser une classe à la place.

**Comment by Royoyo** [comment]
en effet, c'est bien plus logique! ^^'
Changement effectué : d409e5f21ec22994403c7967fd3e4bd668b9333a

**Comment by taophp** [comment]
C'est mieux. Essayez de n'utiliser qu'un seul fichier css pour toute la maquette, cela sera plus facile à gérer. (On peut charger un fichier css dans un répertoire supérieur à celui où on se trouve en utilisant `../` dans le chemin.
