### ISSUE TITLE
HELP ME PLEASE

### ISSUE THREAD

**Issue by Draimon** [Royoyo/ProjetSio#33]
@Royoyo  @nicolasdeu  @Kevin-niva  @Romain-Spielmann 
Les gars, je voudrais que pour mon identifiant lescaractères spéciaux soient interdit. Comment faire? y a t-il un type ou une verif javascript, mon collègue ma parlé du keydown et keyup....
Merci de me répondre ce matin

**Comment by Romain-Spielmann** [comment]
J'ai un truc qui conviendrais, mais il y a peut-être plus efficace
<input type="text" onkeyup="this.value=this.value.replace(/[^a-zA-Z0-9]/ig, '');" />

Le javascript remplace tout les caractère qui sont pas alphanumérique par rien, en gros il efface les caractère spéciaux/espaces.

**Comment by Draimon** [comment]
Ok mais sa je le colle ou????

**Comment by Draimon** [comment]
C'est bon safonctionne merci romain
