### ISSUE TITLE
Petite question

### ISSUE THREAD

**Issue by Draimon** [Royoyo/ProjetSio#34]
@Royoyo  @nicolasdeu  @Romain-Spielmann  @Kevin-niva  @taophp 

Les gars, j'ai changé mon avatar sur le site mais il ne s'est pas changé automatiquement sur l'app vous auriez la solution?
J'ai cherché sur google mais sans réussite

**Comment by taophp** [comment]
J'imagine que tu parles de Github ?
Aucune idée, mais il suffit peut-être d'attendre. Les synchronisations faites par les apps sont rarement immédiate, surtout pour des données aussi importante. Cela peut être une fois en 24 h dans certains.

**Comment by Draimon** [comment]
a d'acc j'ai juste à attendre on verra bien la semaine pro. Avez vous vus mes commits?

**Comment by taophp** [comment]
Oui. :) Voir #37
