### ISSUE TITLE
Problème caractères accentués

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#35]
Dans les fichiers https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Pages%20Login/creation-compte-Damien.html ligne 48 et https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Pages%20Login/reinitialisation-mdp-Damien.html ligne 4, tu utilise des séquences HTML de remplacement pour les caractères accentués. Rien à dire là dessus, mais tu oublies que ces séquences **doivent** se terminer par un point virgule pour être reconnus.
Ainsi, par exemple:
* `&icirc` affichera &icirc
* `&icirc;` affiche î

Merci de corriger.

**Comment by Draimon** [comment]
Aaaaaaaaaa j'en savais rien merci

Damien Raimon

**Comment by Draimon** [comment]
Voilà c'est réglé eten fait chromene m'affichait pas ce problème, c'est pour cela que je ne m'en suis pas rendu compte

**Comment by taophp** [comment]
Une bonne pratique consiste à laisser l'auteur d'un ticket le fermer lui-même s'il est satisfait de la réponse. Après s'il ne donne pas signe de vie pendant longtemps, et qu'on l'a relancé au moins une fois, on peut le refermer tout de même.

**Comment by Draimon** [comment]
C'est noté

Damien Raimon
