### ISSUE TITLE
Suppression du champ email dans le formulaire de création de compte ?

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#36]
Au commit https://github.com/Royoyo/ProjetSio/commit/3a866be63709da2906e73444f0c6a05076c65d70 je constate que des champs qui étaient en place dans le formulaire de création de compte pour saisir l'email de l'utilisateur et sa confirmation ont été supprimés.
Étant donné que pour que les procédures d'[initialisation](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#processus-dinitialisation-de-compte) et de [réinitialisation](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#r%C3%A9initialisation-du-mot-de-passe) de compte fonctionnent correctement cette donnée est absolument nécessaire, je me demande à quelle moment de la procédure de création de compte vous comptez la recueillir.

Au cas où il s'agirait d'une erreur, merci de rectifier. Sinon, merci de clarifier.

**Comment by Draimon** [comment]
Désolé mais l'identifiant n'est pas un mail, enfin c'est ce que Guillaume m'a expliqué, du coup je vouslaisse voir sa avec @Royoyo Merci

**Comment by taophp** [comment]
Merci de ne pas refermer le ticket avant d'avoir au moins l'impression que tes explications pourraient me convenir. Si tu estimes qu'il concerne quelqu'un d'autre, merci de lui affecter.

Ce n'est pas parce que l'identifiant n'est pas un email qu'on a pas besoin de l'email pour pouvoir activer le compte ou réinitialiser le mot de passe.
Merci de se référer aux points du cahier des charges indiqués dans le ticket.
Il **faut** corriger ce point.

**Comment by Royoyo** [comment]
Ce ticket n'ayant plus de sens, je le ferme pour plus de lisibilité sur l'avancement du projet
