### ISSUE TITLE
Formulaire incohérent avec le cahier des charges

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#37]
Dans le cahier des charges, il est prévu que la [création de compte utilisateur soit une fonctionnalité réservée à l'administrateur](https://github.com/Royoyo/ProjetSio/blob/master/Cahier%20des%20charges/Cahier%20des%20charges.md#cr%C3%A9ation-dutilisateurs). Cela a été confirmé auprès du client en #9 .
Pourtant en lisant le formulaire écrit par @Draimon , j'ai l'impression qu'il pense à une création à l'initiative de l'utilisateur.
Mais peut-être est-ce seulement une étape de conception?

Merci de voir avec lui ce qu'il en est puis de m'expliquer ou de corriger.

**Comment by Draimon** [comment]
Je confirme que je pense que c'est l'utilisateur qui crée son compte....

**Comment by taophp** [comment]
Ce n'est pas le cas. Merci de lire le cahier des charges, au moins sur les points concerne les tâches qui te sont affectée.

**Comment by taophp** [comment]
@Draimon à corriger donc.

**Comment by Draimon** [comment]
Chere Mr Mourrey, 
je suis quelqu'un de très cool, mais vos façon de répondre sont assez directes et pas vraiment agréables. Je fais l'effort de me bouger pour ce projet(en ayant je vous le rapelle aucune connaissance en dév), je ne pense pas que beaucoup de mes camarades (autres que systeme et reseaux) aient fais vivre le projet. Alors que faire? Participer et voir des reponses a mes issues agressives? Ou bien tout simplement ignorer ce projet comme plus de la moitié de la classe?
A vous de me dire par ce que là je suis carrément gavé par ces posts. Ce n'est peut-être pas fait exprès de votre part mais bon.
Je me permet de partager cet e-mail avec mes camarades.

Cordialement,
Damien Raimon

**Comment by Draimon** [comment]
@Royoyo  @nicolasdeu  @Romain-Spielmann  @Kevin-niva

**Comment by Royoyo** [comment]
@Draimon  : 

D'abord, parenthèse par rapport à ton coup de gueule :

Il est vrai que Mr Mourey répond de manière directe et critique dès qu'il y a des erreurs dans nos commits...Mais c'est normal, vu que son travail pour ce projet est de vérifier que ce que nous faisons correspond bien au cahier des charges, non? 
(Je peux t'assurer que Mr Mourey a critiqué à peu près tout ce que j'ai écris au moins une fois.)

C'est très bien que tu sois motivé et que tu participes, ça me rend bien content moi en tout cas de voir que les gens se bougent enfin ^^ , mais n'oublie pas que Mr Mourey prend de son temps libre aussi pour faire avancer  ce projet, il n'est pas obligé de vérifier tout ce qu'on fait pour pointer le doigt sur la moindre erreur! ( ce qui est plutôt une bonne chose de mon point de vue, car il partage son expérience avec nous)  En plus je vois dans les tickets fermés qu'il a répondu rapidement à plusieurs de tes questions !

Maintenant revenons au projet : 

* Déjà : Je vois que tout ça découle d'un quiproquo [ici](https://github.com/Royoyo/ProjetSio/issues/36). Mr Mourer pensait que tu allais faire la page de création de l'administrateur, alors que je t'ai demandé de faire c'est la page de login. 
* On en vient au sujet d'ici : non ce n'est pas l'utilisateur qui va créer le compte. C'est seulement l'administrateur qui aura cette capacité. En créant le compte il va générer un lien d'activation et l'envoyer vers le mail du futur utilisateur. ( d'ou la demande d'un champ mail) J'ai déjà demandé à @Romain-Spielmann  de faire cette page ([ici](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Pages%20Administrateur/create.html)
* Pour en revenir aux pages qu'il faut que tu fasses : je t'ai demandé de faire la page login et la page réinitialisation de mot de passe. Pas de page de création ^^. 
  Je t'avais rappelé que c'était  une page de login [ici] (https://github.com/Royoyo/ProjetSio/issues/32)  mais vu que j'ai fermé le ticket avant que tu répondes tu ne l'as peut être pas vu. My bad.
* Dernière chose : c'est Mr Mourey qui a écris le cahier des charges, donc il y a de grandes choses qu'il sait mieux que moi ce qui doit être fait pour ce projet et comment cela doit être fait. Dans le doute (comme avec l'identifiant), dis toi que c'est lui qui a raison.

@taophp Est ce que vous pouvez mettre des smileys dans tout vos messages pour rendre les critiques plus facile à supporter? :)

Voilà, j'espère avoir bien compris la situation, je ne serai pas disponible avant 21h ce soir pour répondre.

**Comment by Draimon** [comment]
Merci de ta reponse @Guillaume mais dit moi? On est combien a contribuer au projet? En dejors des dev, il y a daniel et moi. Les autres, tranquile, ils n'ont même pas installé github et ils sont penard. Perso j'ai pris du temps sur mes pauses et entre midi et deux pour faire ce taff, je sais que j'ai rien fais d'énorme mais crois moi quand je te dis que j'ai passé 20mn pour faire un "é" en HTML. Alors je ne supporte pas que l'on me reponde de maniere aussi seche, c'est simplement demotivant. Voila en esperant que le message passe et soit compris

Damien Raimon

**Comment by taophp** [comment]
@Royoyo @nicolasdeu @Romain-Spielmann @Kevin-niva et plus particulièrement @Draimon

Je reproduis ici le comportement que j'ai expérimenté en milieu professionnel. Dans un ticket, sauf exception comme ici, on se doit de se limiter aux faits. Quelle chose chose en va pas, on le dit le plus simplement possible, le plus clairement, le plus efficacement. Si quelque chose est bien, on ferme le ticket avec un court commentaire de remerciement ou de satisfaction, parfois même sans rien dire. Évidemment, quand on est le prestataire et qu'on s'adresse au client, on y met un peu plus les formes, mais pas tant. Si on ressent le besoin d'y mettre les formes, parce que le client est susceptible par exemple, on préférera utiliser un autre média, mail ou téléphone, qui à suivre le truc à part dans un ticket auquel le client n'aura pas accès.
La sécheresse est inhérente au système de tickets et à l'efficacité recherchée. Ce qui s'y trouve ne doit avoir rien de personnel, autant que possible, car un ticket est susceptible, selon la structure, d'être affecté par plusieurs services, parfois sur des continents différents (auquel cas l'anglais est imposé... ce dont je vous dispense).
Je considère que, pour une part non négligeable,  l'intérêt de cet exercice tient à son côté "jeu de rôles", c'est-à-dire que nous jouons chacun à adopter une position fictive correspondant à une position réelle existante dans le milieu professionnel. Ici, je joue le rôle du chef de projet côté client, je dois gérer un budget et une planification. @Royoyo a le rôle de chef de projet côté prestataire, il a les mêmes responsabilités, mais en plus il doit gérer l'équipe et la répartition des tâches. @Draimon tu joues le rôle d'intégrateur web. On a de la chance qu'il n'y ait pas de commercial dans l'affaire, qui tiendrait le rôle de @Royoyo.
Bref, dans mon rôle, je n'ai pas à être _gentil_, j'ai à être _satisfait_.

En dehors de ça, il est normal que le développeur se fasse reprendre plusieurs fois, souvent sèchement, dans son travail. Ça m'est arrivé maintes fois. Souvent, mon patron trouvait que c'était trop souvent malgré le mal que je pouvais me donner, m'affirmant que je n'avais même pas testé ce que souvent j'avais testé avec patience. Je peux te dire que le ton était souvent cassant, sans que ça tienne à moi, parce qu'avec les autres, c'était pas forcément mieux. Ça n'empêchait pas de s'entendre plutôt bien par ailleurs, de savoir rigoler, manger ensemble à ses frais, bref, de faire la part des choses et de savoir s'apprécier au delà des difficultés qu'on rencontre dans le taf.

Donc, le ton du ticket n'a rien de personnel, ce n'est pas même un prof qui s'adresse à son élève, mais un client à son prestataire.

Par ailleurs, je n'avais pas spécialement l'intention de regarder tes commits, en principe je pensais attendre la sollicitation de @Royoyo pour que je valide le travail accompli. @Draimon tu m'as demandé en #34 si j'avais bien vu tes commits. Donc j'ai pris sur mon temps pour regarder et signaler soigneusement ce qui me semblait clocher.

Je prends moi aussi sur mon temps de "loisirs", je veux dire que je ne suis pas payé pour ça. Je n'ai aucun intérêt personnel dans ce projet, il ne m'intéresse pas spécialement. Je le fais d'une part pour rendre service à monsieur Mosin, qui a besoin de cet outil, et pour **vous**, car cela trouve sa place dans votre parcours de formation, qui n'est pas seulement technique mais aussi comportementale : savoir travailler en équipe avec des gens qui ont des attitudes différentes, qui ne sont pas toujours très cool ou pas très encourageante, ça fait partie du taf. L'intelligence consiste à savoir faire la part des choses, et quand on se retrouve au bar, laisser ça de côté, se fendre d'une bonne rigolade.

Voilà, j'essaie simplement de vous rendre service, en étant le plus efficace possible, pour vous comme pour moi, je dis les choses comme elles sont parce que c'est de **mon** temps que je vous consacre, je n'y gagne rien et je vous apporte quelque chose. Si vous trouvez qu'en plus je devrais mettre un emballage cadeau, alors, s'il vous plaît, ne faites pas ce métier, vous êtes trop susceptibles.

Enfin, sur ceux qui ne font rien, ils sont majeurs, je ne vais pas leur courir après un par un. Ils se pénalisent eux-mêmes et je ne vais certainement pas m'épuiser à les pousser pour faire chaque pas que je leur demande. Je ne les méprise pas pour autant, même si naturellement, ils ne monteront pas dans mon estime comme cela.

@Draimon si tu veux savoir *réellement* ce que je pense de toi : ton enthousiasme est porteur pour moi et je me réjouis de chacun de ces mercredis que je dois passer avec vous en grande partie pour cela.

Voilà, j'espère que j'ai clarifié la situation et que j'ai été assez gentil pour qu'on puisse se remettre au travail sans se demander si le ton des uns et des autres est approprié ou pas, dans la vie professionnelle il ne l'est pas toujours non plus :  **l'essentiel est ce qu'il y a à faire et à apprendre**.

**Comment by Draimon** [comment]
Content d'apprendre qu'en fait ce projet est un jeu de rôle, je n'étais  pas au courant, peut être que les autres eux le savait...
Dans tous les cas je n'ai pas la même vision du monde du travail que vous certainement. J'ai dans mon passé géré des équipes allant de 5 à 20 personnes selon les périodes. Et je peux vous dire qu'ils avaient beau être rémunéré pour leur travail, que je ne me serais jamais permis de leur parler de manière agressive ou sèche, la cause ( je sais pas? Les prud'hommes  peut être ?). Sachez que nous suivions tous les 6 mois de nouvelles formation en management afin d'apprendre a les motiver et non pas les réprimander. Si vous voulez passer pour le client je pense que si le client s'y connait autant, il n'a pas besoin de nos service, donc ne m'en voulais pas de rester dubitatif face à votre réponse. J'espère bien que nous pourrons prendre un peu de temps afin de discuter tous les deux mercredi. Passez une bonne soirée.
Cordialement,

Damien Raimon

**Comment by taophp** [comment]
J'ai été sec, jamais agressif. Je n'ai réprimandé personne.
J'ai indiqué plusieurs fois que nous tenions des rôles, demande à @Royoyo. Par ailleurs, la situation pédagogique veut que nous simulions des situations d'entreprise, c'est explicitement indiqué dans le référentiel en ce qui concerne les PPE. C'est ce que j'appelle un jeu de rôle.

J'ai 25 ans d'expérience du travail dans des métiers et des lieux variés, et je peux te dire que des mecs qui sont formés à l'encadrement tous les 6 mois pour motiver leurs troupes, je n'en ai pas connu. Je ne dis pas qu'il n'y en a pas, mais la plupart de mes chefs n'ont même jamais été formés à l'encadrement, et c'est quelque chose de fréquent dans le monde du travail. Je pourrais aussi te parler de l'expérience de ma femme, aussi longue et variée que la mienne, mais bien plus terrible. Un encadrement maladroit, c'est très fréquent : il faut pourtant savoir faire avec, car à la fin, c'est toi qu'on juge sur ton boulot, plus rarement ton chef sauf si le problème se généralise (et encore).

Personnellement, puisqu'on en vient sur ce terrain, je n'aurai sans doute pas accepté un poste d'encadrement : j'ai déjà du mal à assumer mes propres responsabilités, alors être responsable des autres... La situation d'enseignement me parait différente. L'année dernière, je me suis fais de véritables angoisses parce que je me sentais responsable de ce que faisaient (ou plutôt ne faisaient pas) les apprenants. Jusqu'à ce que je comprenne que je n'avais tout simplement pas de prise sur eux, qu'on ne force pas à boire un âne qui n'a pas soif.

Damien, ce que je fais quand j'enseigne, c'est un cadeau. Ne crois surtout pas que je le fasse *pour* l'argent, je n'en ai pas besoin. Je le fais parce que je pense que mon existence a plus de sens si je partage ce que je sais que si je le garde pour moi. Je le fais aussi pour le plaisir de vous connaître, et de te connaître toi en particulier, parce qu'il faut bien le dire, du haut de ma tour de Mage, je me sens parfois un peu seul.

Enfin, pour en revenir à l'exercice du ticket : je t'ai paru sec parce que je me suis contenté d'énoncer les faits tels que je les voyais de mon point de vue, et il me semble que c'est ainsi que les tickets doivent être rédigés, même si on s'autorise parfois quelques écarts. En effet un ticket n'est attribué à une personne que temporairement et peu être réaffecté à bien des personnes qui auront d'abord besoin des faits et de leur succession pour faire leur travail. Il y a parfois eu des dizaines d'échanges quand le ticket t'es affecté, et tu n'en as peut-être jamais entendu parler. Si tu dois te taper des pages dans lesquelles tu devrais faire le tri en ce qui est fondamentale et ce qui simplement politesse ou discours privé (exactement ce qu'on est en train de faire), tu risques de louper un point essentiel perdu dans des choses ayant peu ou pas de rapport. On apprécie éventuellement le travail quand il est terminé et qu'on ferme le ticket pour dire "Cool les gars, je suis content qu'on ait résolu le problème ensemble, vous m'enlever une belle écharde du pied". En attendant, on essaie de s'en ternir aux faits, aux problèmes et aux solutions. Ce qui sort de cela est à faire en priorité par un autre média, privé, par oral, téléphone, mail ou chat par exemple. Utiliser un système de tickets n'interdit pas de telles conversations, même si, dans le cas où un fait important apparaît dans ses communications, il faut le consigner dans le ticket et le référencé pour pouvoir justifier et valider ("lors de notre conversation téléphonique du..., confirmez-vous cette demande?", "dans votre mail du...").

Un ticket est un document de travail, souvent partagé avec le client, parfois même publique comme pour nous ici. Au delà des nécessités de travail que je viens d'indiquer, une réserve plus importante encore, s'impose. Le ticket peut même avoir une dimension contractuelle dans la mesure où le client valide un travail ou effectue des demandes, et à ce titre être produit dans un tribunal en cas de litige.

Je n'ai personnellement dérogé à ces règles ici que parce que nous sommes dans une situation pédagogique à distance et que ce que j'ai à dire peut aussi servir aux autres. En entreprise, j'imagine qu'on se serait peut-être pris la tête 5 minutes autour d'un café et que les choses auraient été rapidement mieux.

**Comment by Draimon** [comment]
Merci pour ces réponses, alors suite a une discussion avec mes autres collègues SIO (en particulier Option Dév) il m'est apparu que le problème vient de moi, ils ne vous ont pas trouvé particulièrement sec, du coup c'est peut être moi qui l'ai mal pris tout simplement sans raison. Veuillez du coup m’excuser de cette polémique, j'essaierai de moins prendre à coeur les tickets et de les voir de manières plus subjectives. Méacoulpa Mr Mourrey, à Mercredi, Par contre je demande un petit brief par ce que du coup j'ai rien compris à ce que je devais faire en fait

**Comment by taophp** [comment]
Aucun souci @Draimon. On fera le point avec @Royoyo mercredi: il a dit qu'il y avait un quiproquo. La page qui m'a fait réagir ici était dans ce commit https://github.com/Royoyo/ProjetSio/commit/4fb3fff7bb1cff91745fe4174cc527587e99b822 le fichier ProjetSIO/HTML/Pages Login/creation-compte-Damien.html : comme il s’appelle "creation-compte-Damien.html", je me suis imaginé, je ne sais pourquoi qu'il traitait de la création du compte. Il semblerait que ce ne soit pas le cas. De l'importance de bien choisir ses noms de fichiers et de variables...

**Comment by Draimon** [comment]
Tout à fait d'accord mais au départ je pensais réellement faire une page de création de compte mais qui devais ressembler à une page de login du coup ça à donné ce mix ^^. Je viens de modifier tous ça, je vous laisse voir le résultat sur mes derniers commits. Bien à vous.

**Comment by Royoyo** [comment]
Je ferme  le ticket vu que la hache de guerre a été enterré et que le quiproquo  est levé .
