### ISSUE TITLE
Vue Admin - Pages années scolaires 

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#38]
J'aimerai que fasses toutes les pages en rapport avec l'affichage, la création et la modification des années scolaires. Tu peux trouver les infos en rapport avec ce que je te demande de faire dans la section "gestion des années scolaires" dans le cahier des charges.

Tu peux bien entendu réutiliser le tableau que tu as fait pour la page d'affichage des utilisateurs.

**Comment by Royoyo** [comment]
Il faudrait que tu penses à mettre le commit ici quand il a un rapport avec le ticket.
Je présume que c'est celui là : 6e94c495357767a721a02d6476135c61be2ef066

Je vois que tu as fait la création d'une année + la vue calendrier de l'année. Très bien.

Je vois deux choses qui manquent :
* Il manque de quoi rendre l'année scolaire inactive.
* une page pour sélectionner l'année scolaire que l'on souhaite modifier.  Un simple tableau dans lequel elles seront listées devrait faire l'affaire.

Petite pensée : Il serait idéal que la page qui liste les années scolaires puissent avoir ces raccourcis pour chaque année : 
* Un lien qui mène vers la page calendar que tu as créé pour montrer les jours de fermeture ( pas très efficace mais on garde pour l'instant)
* Un lien de modification de l'année ( qui mène vers ta page de création en version modification)
* Un lien qui mène vers la liste des semaines de cette année scolaire ( pour la gestion des semaine d'enseignement ) 

Pour ce dernier lien consulte les deux dernières sections de "Fonctionnalités du Planificateur" du cahier des charges. Il faudra faire quelques pages en plus. ^^

**Comment by Romain-Spielmann** [comment]
J'ai commiter les pages : 4541287338c98da7479f2a2799f229a5f051977d

Il me semble que tout est là sauf le lien pour mener vers la gestion des semaines, je ne savais pas trop où la mettre.

**Comment by Royoyo** [comment]
Quand je parlais de liste des semaines pour une année je pensais à quelque chose de ce genre là : 
![exemple tableau semaine](https://cloud.githubusercontent.com/assets/6312371/6235946/848f2dae-b6e6-11e4-9f9a-4ea8e58e6f28.png)

puis tu cliques sur la semaine et la classe pour modifier le planning de cette classe pour la semaine
