### ISSUE TITLE
Vue Enseignant - Page Consultation de sa planification

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#39]
Je te donne une autre page à faire.

Tu trouveras les infos utiles tout à la fin du cahier des charges. 

Si tu as des questions n'hésite pas!

**Comment by Kevin-niva** [comment]
Je prends note guillaume, je vais me pencher doucement dessus. 
As-tu en tête une deadline pour le rendu final de la page histoire que je puisse planifier mon temps? Merci.

**Comment by Royoyo** [comment]
Je peux te demander ça pour le courant de la semaine prochaine?

**Comment by Kevin-niva** [comment]
ça devrait être jouable

**Comment by Royoyo** [comment]
T'as réussi à avancer un peu sur ta page? Je sais que t'as pas internet pendant la semaine mais n'oublie pas de commit dès que tu rentres!

**Comment by Royoyo** [comment]
ton commit : d6a3d422cac899e6fb54ff1d6ebffdfe564c137f

Enfin! ^^

Alors je vois deux problèmes : 
* je ne vois pas la div avec l'id content , elle fait parti du template, il faut qu'elle soit là!
* ta balise meta s'affiche sur la page en clair, faut coller l'ouverture de la balise au mot "meta"

**Comment by ZeroAbsolu** [comment]
J'ai modifié un peu mais la vu l'heure je remet pas ça en etat de suite, je viens de faire 3 commit pour au final faire une chose tellement j'arrive pas à réfléchir, ça risque de faire n'importe quoi en fait^^

**Comment by Royoyo** [comment]
ça me parait bon : 7a02185de6fd434425fd7ddec0912fee211a52e7

Je ferai le style du tableau moi même donc c'est bon.
