### ISSUE TITLE
Point sur l'évolution de la situation

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#41]
J'aimerai un point sur l'évolution depuis la dernière fois que nous nous sommes vus en cours. Quelque chose a-t-il bougé ? Je n'ai pas vu de création de tickets suite aux remarques que j'avais faites en cours...

**Comment by Royoyo** [comment]
Je n'ai pas eu le temps de prendre en compte vos remarques ou même de vérifier les commits des autres, étant assez occupé depuis la semaine dernière...En plus de cela , la grippe ne m'a pas loupé ce qui n'aide pas. 

Je me suis donné un peu de temps demain soir pour faire une review global de ce qui se passe sur le projet et de "factoriser" un peu les efforts de tous le monde. Vous aurez les réponses à vos questions à ce moment.

**Comment by Royoyo** [comment]
J'ai crée une issue pour suivre l'état global du projet [ici] (https://github.com/Royoyo/ProjetSio/issues/42) 
Pour l'instant 4 sur 18 pages HTML sont prêtes pour la maquette fonctionnelle

**Comment by taophp** [comment]
Ok. Super.
