### ISSUE TITLE
Éviter l'utilisation de ressources externes

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#45]
J'ai constaté à plusieurs endroits de la maquette, dans le head, cette ligne:
```html
<link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
```
Je souhaiterai qu'on évite d'utiliser des ressources extérieures autant que faire se peut.

**Comment by Royoyo** [comment]
Oui , je connais votre avis sur la question, j'ai prévu de rendre ces ressources locales.

**Comment by Royoyo** [comment]
J'ai rendu l'utilisation du font totalement local : 7bcee009293bafedc1a947f273be58801ad18215

**Comment by taophp** [comment]
Modifier le CSS, c'est bien, faut-il encore supprimer les lignes incriminées dans le ticket...

**Comment by Royoyo** [comment]
Les lignes ont été supprimées dans les commitsa4b4c1b99197c3cadcf39e864dc9d5629bffa5fe et 472a2d937e371e63c923f42acbff970c25cc9e08

Je ne voyais pas vraiment de moyen de séparer les changements dans un même fichier en deux commits différents, c'est pour cela qu'il n'y a que les fichiers rendant le font local dans le commit 7bcee009293bafedc1a947f273be58801ad18215

**Comment by taophp** [comment]
Ici : https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/HTML/Pages%20Administrateur/consult.html ligne 9.
Il y en a probablement d'autres. Le mieux pour les trouver (sous Linux) est sans doute d'utiliser la commande `grep`:
```bash
grep -nri googleapis *
```
à la racine du projet.

**Comment by Royoyo** [comment]
Ok.  Je vais nettoyer tout  ça. Mais l'idée,  une fois que le projet
passera à un rendu dynamique avec php,  est bien que ce head  ne soit
stocké  qu'à  un seul endroit non ?  Est ce grave s'il y quelques
inconstances ( qui  n'influe pas le visuel)  lors de la création de la
maquette fonctionnel ?  Je demande ça par rapport à une situation réelle.

**Comment by taophp** [comment]
Non, c'est sans gravité. C'est juste qu'il ne faut pas confondre ce qui est fait de ce qui est à faire. Tu as même le droit de mettre le ticket en attente, de planifier sa résolution pour plus tard, et de me dire voilà, c'est comme ça que je veux régler le problème. Je pourrai toujours te dire ce que j'en pense, si je suis d'accord ou pas et pourquoi. Mais tout ça, il faut le mettre dans le ticket, sans quoi, il pourrait y avoir un malentendu. Imagine que je sois contre utiliser des ressources distantes dans la maquette que je présenterai au client ? Ce pourrait être le cas si les contraintes de sécurité étaient **très** élevées. En tous les cas, il faut que je puisse m'exprimer par rapport à tes décisions.
