### ISSUE TITLE
Ergonomie de la saisie des indisponibilités

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#46]
Sur la page : http://guillaumehaag.fr/SIO/Projet/Pages%20Enseignant/indiquer_indisponibilitees.html
Il faut revoir l'ergonomie. En effet, utiliser une liste déroulante "Type d'indisponibilité" pour basculer entre les modes "Après-midi/matin/jour" ne permet pas d'avoir une vue d'ensemble. Il faut pour chaque jour, une case à cocher pour le matin et une pour l'après-midi.

**Comment by Royoyo** [comment]
j'ai demandé à @Romain-Spielmann  de s'occuper de cette tâche dans ce [ticket](https://github.com/Royoyo/ProjetSio/issues/52)
