### ISSUE TITLE
Ergonomie des plannings enseignants

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#47]
http://guillaumehaag.fr/SIO/Projet/Pages%20Enseignant/verifier_sa_planification.html
Un texte n'est pas très explicite et en tout cas pas visuel. Il faut un tableau HTML avec le planning de la période entière, même si c'est pour laisser surtout du vide.

**Comment by Royoyo** [comment]
Qu'est ce que vous entendez par période entière?

**Comment by taophp** [comment]
Je ne sais pas, j'ai juste cliqué sur "Consultation de mes cours", je n'ai pas eu à choisir de plage de date, mais j'ai tout de même un affichage de la planification avec deux dates extrêmes : du 2 au 13 février. Mais j'imagine que cela correspond aux cours à venir...

**Comment by Royoyo** [comment]
C'était un simple exemple. La page est fixe.  En général un professeur à
combien de cours à venir qui lui sont  assigné  à un point donné ?

**Comment by taophp** [comment]
Aujourd'hui, un prof a une visibilité d'environ 2 mois ce qui est peu. J'espère pour ma part qu'avec un outil plus performant, on pourra avoir une visibilité bien plus élevée, l'idéal serait de pouvoir anticiper toute l'année scolaire en cours.
La maquette est toujours un simple exemple, mais devant illustrer autant le contenu que l'ergonomie. Ici, pour moi, l'ergonomie n'est pas idéale.
