### ISSUE TITLE
Ergonomie consultation du planning de mes classes

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#48]
http://guillaumehaag.fr/SIO/Projet/Pages%20Enseignant/voir_semaine_classe.html
À quoi servent les listes déroulantes si on est en simple consultation ?

**Comment by Royoyo** [comment]
C'est la même page que pour la planification. Je pensais que ça suffirait pour la maquette. J'enlèverai les listes déroulantes dans la journée.
