### ISSUE TITLE
Demande de validation de la maquette

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#51]
Bonjour cher client,

Le travail sur la maquette est maintenant en cours de finalisation. Il reste bien quelques petits détails à revoir, quelques tickets restent encore ouverts, mais l'ensemble est correct et donne une image satisfaisante de la future application.
Je vous invite donc à en prendre connaissance et à nous faire part de vos remarques, questions ou demandes à l'aide de tickets, chaque ticket ne traitant que d'un seul point et ne regroupant pas plusieurs problématiques.

L'accès à la maquette se fait à cette adresse : http://guillaumehaag.fr/SIO/Projet/Pages%20Administrateur/modif.html
Trois liens figurent en bas de page, permettant de découvrir l'application de trois points de vue différents, correspondant à des rôles d'utilisateurs et des droits différents. Dans l'application finale, un utilisateur sera susceptible de cumuler plusieurs rôles.
Enfin, les liens en entête de page, le menu, ne sont pas fonctionnels à ce jour pour des raisons techniques.

Quand et si tout vous conviendra en terme de présentation et d'ergonomie, et que vous aurez la conviction qu'une application conçue avec ces interfaces vous offre toutes les fonctionnalités que vous en attendez pour cette première réalisation, merci de bien vouloir fermer ce ticket, à partir de quoi nous passerons à la réalisation proprement dite.

Cordialement,

Stéphane Mourey

**Comment by supformation67** [comment]
Bonjour aux développeurs

J'ai découvert aujourd'hui la maquette et je suis enthousiasmé : simple et intuitive, pratique, prise en main aisée... Bravo à tous ! Vous êtes sur les bons rails.
Quelques remarques :
- prévoir un accès élèves au + simple pour accéder aux plannings correspondants à leurs section
- idem pour un accès tuteur pour accéder au planning correspondant à l'élève suivi
- prévoir une alerte mail+sms pour toute planification ou modification adressée aux professeurs concernés avec un rapide aperçu de la planification et les invitant à prendre connaissance du nouveau planning.

Encore bravo !

Didier MOSIN

**Comment by taophp** [comment]
@Royoyo : il faut maintenant traduire les demandes du client en tickets, les affecter, les planifier... répondre et commenter s'il y a lieu.

**Comment by taophp** [comment]
@Royoyo : dans le cas présent, il faudra à la fin de chaque ticket demandé la validation du client avant sa clôture et, lorsque tous les tickets auront été validés, on pourra considérer la maquette validée dans son ensemble et fermer ce ticket-ci. Sur un projet plus lourd, impliquant plus d'acteurs, il serait préférable de redemander une validation d'ensemble, mais je crois qu'ici nous pourrons nous en passer - sauf si le client le demande... n'est-ce pas @supformation67  ?
