### ISSUE TITLE
Partage des tâches

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#53]
(J'ai fermé tous les tickets jusqu'à maintenant vu que l'application a fondamentalement changé)

Bon, j'ai  refait en partie l'interface avec angular-js. (commit ici : 759d1bd1a418236c1ef472f4c81b9d349ca133a6)
On peut retrouver la maquette fonctionnelle en ligne ici : http://guillaumehaag.fr/SIO/PPE

Maintenant qu'on est plus que 4 à travailler dessus, le partage des tâches sera beaucoup plus simple!

Je vais faire un partage un peu plus précis plus tard, mais pour l'instant je vais mon contenter de couper le gâteau en trois grosses parties : 
* Refaire/faire l'interface  ( outils : html/css/angularjs)
* Créer le backend  ( outils : php/ slim framework / création d'objets)
* Créer la base de données ( en commençant par un schéma MCD!)

(Pas une priorité toute de suite : Créer l'interface android! ( outils : java, android studio))

L'idéal serait que vous répondiez ici en classant ces trois parties selon votre ordre de préférence, ça sera plus simple pour moi d'assigner les tâches.

Exemple pour moi :
* 1 Interface
* 2 Backend
* 3 BDD

@ZeroAbsolu  @Romain-Spielmann  @nicolasdeu

**Comment by Royoyo** [comment]
Bien sûr les ces trois parties sont pas tout ce qu'on va devoir faire. J'ai laissé de côté les trucs annexes comme la documentation technique, le schéma UML , le guide utilisateur...

**Comment by Romain-Spielmann** [comment]
1. Backend
2. Front-end / BDD

**Comment by nicolasdeu** [comment]
1. BDD 
2.Interface
3.Backend

**Comment by ZeroAbsolu** [comment]
1) BDD / Backend
1648645345) Interface

**Comment by micheldiemer** [comment]
4 personnes, chacun a fait quelque chose pour ce projet
