### ISSUE TITLE
Implémentation du backend

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#55]
J'ai commencé l'implémentation du backend avec ce commit : a04650bcc3b3ee4f8709522c84358ceec369eab9
Le fichier important est celui là : https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/Backend/index.php

Il y toute la logique de routage des requêtes de données qui va se mettre en place ici, j'ai déjà mis quelques exemples en place.

Vous pouvez voir le résultat en live ici: http://guillaumehaag.fr/SIO/PPEBackend

Ce qui est important à mettre en place ici : 
* Les GET/POST/PUT/DELETE* pour toutes les requêtes
* l'authentification des utilisateurs!
* Quelque chose d'autre que j'ai oublié

\* En gros : GET->SELECT | POST -> INSERT INTO | PUT -> UPDATE | DELETE -> DELETE

**Comment by Royoyo** [comment]
Vu que j'ai pas vraiment indiqué comment on allait faire l'implémentation BDD<->PHP je propose deux choix : 
* Un orm ( je propose celui là : http://laravel.com/docs/5.0/eloquent )
* Des objets et des requêtes préparées 

@Romain-Spielmann  Vu que tu as mis backend comme premier choix je te laisse choisir

**Comment by micheldiemer** [comment]
utilisation de SLIM pour le routing et d'Eloquent de Lavarel comme ORM
