### ISSUE TITLE
problème d'.htaccess avec le backend

### ISSUE THREAD

**Issue by Royoyo** [Royoyo/ProjetSio#56]
Quand je teste en local, les routes sont bien traitées et je reçois mon object JSON si je fais /admin/personnes par exemple. Mais de l'extérieur, à partir de guillaumehaag.fr ça ne fonctionne pas.

J'ai bien activé tout ce qu'il faut sur le serveur apache donc je suppose que c'est un problème avec l'.htaccess (https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/Backend/.htaccess)

Je laisse le ticket ouvert tant qu'on a pas trouvé de solution

EDIT : 
La route de base fonctionne : http://guillaumehaag.fr/SIO/PPEBackend

**Comment by taophp** [comment]
Y a-t-il des écritures correspondantes dans le log d'erreurs de Apache (de mémoire, `/var/log/apache2/error.log` ?
Peux-tu donner un exemple d'URL qui ne fonctionne pas comme attendu ? Tu obtiens une erreur 404, c'est bien ça ?

**Comment by Royoyo** [comment]
Exemple qui ne fonctionne pas:
http://guillaumehaag.fr/SIO/PPEBackend/admin/personnes
Par contre, si j'utilise directement l'adresse ip, ça fonctionne : 
http://92.161.255.178/SIO/PPEBackend

**Comment by Royoyo** [comment]
ah! en passant directement par mon dyndns ça fonctionne aussi : 
http://guillaumehaag.ddns.net/SIO/PPEBackend/admin/personnes

Peut être qu'il y quelque chose qui fait que la requête ne peut pas passer par deux dns?

**Comment by taophp** [comment]
Pour moi, j'ai:
- http://guillaumehaag.fr/SIO/PPEBackend/admin/personnes: erreur 404,
- http://guillaumehaag.ddns.net/SIO/PPEBackend/admin/personnes: serveur not found,
- http://92.161.255.178/SIO/PPEBackend/admin/personnes: du JSON, comme attendu.

**Comment by Royoyo** [comment]
petite erreur de ma part, mon dyndns c'est : 
http://guilaumehaag.ddns.net/SIO/PPEBackend/admin/personnes

avec un seul "l" dans guillaume. ( je m'étais trompé lors de mon inscription ^^')

Ce lien fonctionne?

**Comment by taophp** [comment]
Oui.
Faut que tu envoies ta conf Appache, en particulier /etc/apache2/apache2.conf et les fichiers dans /etc/apache2/sites-enabled (au moins ce qui correspond à ce qui nous intéresse). Attention à ne pas faire apparaitre d'éléments sensibles sur ce ticket, ou alors me l'envoyer par mail.

**Comment by taophp** [comment]
À mon avis, tu dois avoir une conf particulière pour le vhost http://guillaumehaag.fr qui modifie la conf par défaut de telle sorte à empêcher la réécriture d'URL.

**Comment by taophp** [comment]
Je constate que les noms de domaines ne renvoient pas à la même ip:

* `guillaumehaag.fr`: 213.186.33.5
* `guilaumehaag.ddns.net`: 92.161.255.178

S'agit-il de deux machines différentes ou le même serveur répond-t-il aux deux ip ? Y aurait-il sur `guillaumehaag.fr` un reverse proxy ou un CDN ?

**Comment by Royoyo** [comment]
Normalement guillaumehaag.fr redirige vers l'adresse ddns.net. Je vais voir
sur mon compte ovh dès que j'aurai un moment .

Le ven. 18 sept. 2015 08:43, Stéphane Mourey <notifications@github.com> a
écrit :

**Comment by taophp** [comment]
Il faut examiner le contenu de la variable `$_SERVER` avec `var_dump()`. Il faut déterminer ce qui diffère dans cette variable entre les deux façons d'accéder. Comme la réécriture ne fonctionne pas dans un cas, il faut la supprimer temporairement, créer un fichier `index.php` dans un dossier qui imite une url de l'application.

Le script suivant est équivalent à ce que je viens d'écrire:

```bash
mv /var/www/html/SIO/PPEBacked/.htaccess /var/www/html/SIO/PPEBacked/htaccess
mkdir /var/www/html/SIO/PPEBacked/admin
mkdir /var/www/html/SIO/PPEBacked/admin/personnes
echo "<?php" >/var/www/html/SIO/PPEBacked/admin/personnes/index.php
echo "var_dump($_SERVER);" >>/var/www/html/SIO/PPEBacked/admin/personnes/index.php
curl http://guillaumehaag.fr/SIO/PPEBackend/admin/personnes>/tmp/guillaumehaage.fr
curl http://92.161.255.178/SIO/PPEBackend/admin/personnes>/tmp/92.161.255.178
diff /tmp/guillaumehaage.fr /tmp/92.161.255.178
```
Le résultat de la dernière commande devrait fournir l'explication.

**Comment by Royoyo** [comment]
Je viens de faire tout ça.
La seule différence est que pour la requête guillaumehaag.fr le server name est "guillaumehaag.ddns.net et que pour la requête 92.161.255.178 le server name est "92.161.255.178"

**Comment by Royoyo** [comment]
je viens de voir quelque chose de bizarre :
http://guillaumehaag.fr/SIO/PPEBackend/admin/personnes
redirige vers : 
http://guilaumehaag.ddns.net//SIO/PPEBackend/admin/personnes

Avec deux "/" après .net

Alore que : 
http://guillaumehaag.fr/SIO/PPEBackend
redirige vers : 
http://guilaumehaag.ddns.net/SIO/PPEBackend/

D'où peut venir ce problème?

**Comment by Royoyo** [comment]
Bon de toute manière ce n'est pas un problème lié à l'application, mais à la configuration de mon serveur. 
Pour la maquette on pourra simplement utilisé l'addresse ddns.net

**Comment by taophp** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Le problème vient clairement de là. Tu peux t'en assurer en modifiant
la ligne 22 de Backend/index.php
de
  $app->get('/admin/personnes', function () use ($app,$personnes) {
en
  $app->get('//admin/personnes', function () use ($app,$personnes) {


Le 19/09/2015 13:48, Guillaume Haag a écrit :
> je viens de voir quelque chose de bizarre : 
> http://guillaumehaag.fr/SIO/PPEBackend/admin/personnes redirige
> vers : 
> http://guilaumehaag.ddns.net//SIO/PPEBackend/admin/personnes
> 
> Avec deux "/" après .net
> 
> Alore que : http://guillaumehaag.fr/SIO/PPEBackend redirige vers : 
> http://guilaumehaag.ddns.net/SIO/PPEBackend/
> 
> D'où peut venir ce problème?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Royoyo/ProjetSio/issues/56#issuecomment-141654096>
.
>
> 
- -- 
Slogans

Le slogan tue la pensée ! - Les slogans tuent la liberté !

En lire plus ici : http://twitlit.impossible-exil.info/Slogans.html

- ----------------------------------------------------------------------

          * Le Rêve du Cinématographe *
	       Un livre de Stéphane Mourey

Un grand réalisateur, maintenant âgé, regarde un vieux film
muet où jouait son père alors qu'il était jeune comédien à
Hollywood. Dans l'esprit de cet homme revivra l'histoire du
cinéma depuis ses origines, jusqu'à ce que la torpeur le prenne
pour le mener dans un cauchemar... cinématographique.

Trouvez-le ici :
http://www.edilivre.com/le-reve-du-cinematographe-20c8e104a2.html

- ---------------------------------------------------------------------

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBAgAGBQJV/p/RAAoJEE90M2UZOrvwEL0P/2RiBNj6om/0w/4LBYzOACwx
WNnCN8Gbo2vNnA/eLJctoQdJb5npotJr6NwzhS4Yfqcquv0Cx2XRlGcE4asiCtPx
lgq6/bnRYbLR7oq9bSV5S+Vn79cufSiwZWfidaHiJUbF6i0KlzIbvSgwgbOs8jnK
ewSEugxZuyFebTZgZhQ063Ac55469XPHuKrjwXHzRggqeVXGL4jYVKN7mnb3Esdo
844JXuC6iFI6cyDsf4to0Lpy7udGXmXmY6Oml5Yib/lHvP6/9RYDbHcwahU8c9WT
WSZbWdFycrh/7O/ix7/HOMbodOBWgpx1dHCr5P4yYsIQn2vchbPrnMXNf0hQh0Xl
0HSZO1GVL8GFnjcSIA09iOJ1sQgOurMJiWP9AjislV8Rs/h17JFwtHh+jtEZjnMP
zv/+EI/m75xuQRIu2Gfgrspk1VNUsOOeOVGbACArifDrsANBWKRVUVIJX9rb2q4f
X5m4o8X0JEECBnKGdd7xjp0cs/gs2LgKMEL4/e7jHFpf6oREKjiRVXGqjH2POuRl
iBSkVjb+OfMJ43JtMQV5Tzwt2Etk1Kk3ngUoWYKBbSQctBplWNuVJ5yj65+n48a6
U0XnKsV6DyzHI6fNTHqJwOF12tDA/AIFzLAJ25LXbjT3N1P4RpbsxO4pnpp5LKLM
1Et0WTfP0fi0RbiqS6Yr
=zFCo
-----END PGP SIGNATURE-----

**Comment by micheldiemer** [comment]
problème résolu
