### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by micheldiemer** [Royoyo/ProjetSio#57]
Vérifier le paramètre time zone de la base de données

**Comment by Royoyo** [comment]
La time zone sera celle du serveur local à l'ifide, et sera plutôt géré par le php du backend au moment de la sauvegarde d'une date dans la base de donnée

**Comment by micheldiemer** [comment]
timezone non gérée par l'appliation ; n'a pas d'utilité étant donné que l'application ne sera utilisée qu'en France
