### ISSUE TITLE
Créer les milestones

### ISSUE THREAD

**Issue by micheldiemer** [Royoyo/ProjetSio#60]
Le milestone le plus important : la date de fin du projet

Un milestone indiquant la date de fin de développement. Prévoir environ 1 mois de tests intensifs et débogage et rédaction de la documentation.

Des milestones intermédiaires après chaque semaine de cours, par exemple 23/10 6/11 20/11 etc.

**Comment by Royoyo** [comment]
Je vais essayer de mettre en place des milestones d'ici ce week-end.
