### ISSUE TITLE
nom du projet

### ISSUE THREAD

**Issue by micheldiemer** [Royoyo/ProjetSio#61]
1) ProjetSIO est vague et général ... 
si on devait changer le nom maintenant qu'est-ce que ça implique ?

2) Quel nom "commercial" pourrion-nous donner à ce projet ?

**Comment by micheldiemer** [comment]
nom commercial : << Gestion du Planning des Cours de l'IFIDE >>

**Comment by Royoyo** [comment]
1) Je peux changer le nom du projet, mais l'url ne changera pas.

2)  Le nom commercial que vous avez indiqué me semble coller

**Comment by micheldiemer** [comment]
Gestion du Planning des Cours de l'IFIDE 
ok
