### ISSUE TITLE
évolutivité du projet

### ISSUE THREAD

**Issue by micheldiemer** [Royoyo/ProjetSio#62]
Le Cahier des Charges présente un certain nombre de contraintes.
On planifie des demi-journées et le samedi et le dimanche sont fermés.

Si les règles devaient changer, par exempe une planification heure par heure, ou encore l'ouverture le samedi matin, ou des ouvertures exceptionnelles (journée portes ouvertes par exemple avec un cours donné par un professeur qui doit être disponible) ou bien des contraintes de salle (pour tel cours, il faut une salle de classe avec tel équipement), etc.

le projet est-il assez modulaire et évolutif pour pouvoir répondre aux nouvelles exigences ou bien faudra-t-il (presque) tout reprendre à zéro ?

**Comment by Royoyo** [comment]
Le projet tel qu'il est en train d'être conçu va prendre en compte les périodes en stockant la minute de début et la minute de fin de la période, donc même si la précision demandé est par période de 4 heures pour l'instant ( demie-journée de cours) , on pourra facilement faire évoluer l'application à une autre fourchette.

Le planificateur pourra changer ces périodes de fermetures à partir de sa section de l'application web. Il est prévu de faire une différence entre les jours de fermetures exceptionnel et les jours de fermetures répétitifs.

Pour ce qui est des contraintes de salle, aucune demande n'a été faites dans ce sens dans le cahier des charges, donc rien n'est prévu pour cela. C'est un module qu'il faudra développer entièrement et attacher à l'application. ( Rajout des tables/champs à la bdd, des objets dans l'ORM et du traitement dans l'interface)

J'essaie de garder la logique de l'application la plus modulaire possible, pour que l'on puisse facilement rajouter des fonctionnalités par la suite.

**Comment by micheldiemer** [comment]
Si nécessaire il faudra revoir l'interface utilisateur.
