### ISSUE TITLE
[Backend] Mettre en place un fichier par modèle

### ISSUE THREAD

**Issue by taophp** [Royoyo/ProjetSio#63]
Actuellement, tous les modèles se trouvent dans un seul fichier [model.php](https://github.com/Royoyo/ProjetSio/blob/master/ProjetSIO/Backend/model.php).
Il faudrait:
* créer un dossier `classes` destiné à contenir toutes les classes du projet,
* créer un sous-dossier `models` destiné à contenir tous les modèles du projet,
* créer un fichier par modèle dans ce dernier dossier.

**Comment by micheldiemer** [comment]
Les modèles n'ont que peu de lignes grâce à l'ORM. L'intérêt de séparer est donc limité.
